using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KallynGowdy.SyntaxTree
{
	/// <summary>
	/// Defines an interface that represents an element of syntax.
	/// </summary>
	public interface ISyntaxElement : IHasSyntaxTree, IHasSyntaxPosition
	{
		/// <summary>
		/// Gets whether the node represents a language construct that was not actually parsed from the source.
		/// Missing nodes are generated by the parser in error scenarios to represent constructs that should have been present in the source code
		/// in order to compile successfully but were actually missing.
		/// </summary>
		bool IsMissing { get; }
	}
}
